CREATE DATABASE opt_db;

DROP TABLE IF EXISTS opt_orders;
DROP TABLE IF EXISTS opt_products;
DROP TABLE IF EXISTS opt_clients;

CREATE TABLE IF NOT EXISTS opt_clients (
                                           id UUID PRIMARY KEY,
                                           name VARCHAR(255) NOT NULL,
                                           surname VARCHAR(255) NOT NULL,
                                           email VARCHAR(255) NOT NULL,
                                           phone VARCHAR(50) NOT NULL,
                                           address TEXT NOT NULL,
                                           status VARCHAR(20) NOT NULL CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE IF NOT EXISTS opt_products (
                                            product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            product_name VARCHAR(255) NOT NULL,
                                            product_category VARCHAR(50) NOT NULL CHECK (
                                                product_category IN ('Category1', 'Category2', 'Category3', 'Category4', 'Category5')
                                                ),
                                            description TEXT
);

CREATE TABLE IF NOT EXISTS opt_orders (
                                          order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          order_date DATE NOT NULL,
                                          client_id UUID,
                                          product_id INTEGER,
                                          CONSTRAINT fk_opt_orders_client
                                              FOREIGN KEY (client_id) REFERENCES opt_clients(id),
                                          CONSTRAINT fk_opt_orders_product
                                              FOREIGN KEY (product_id) REFERENCES opt_products(product_id)
);

SELECT
    count(*)
FROM opt_clients;
SELECT
    count(*)
FROM opt_products;
SELECT
    count(*)
FROM opt_orders;



EXPLAIN ANALYZE
SELECT
    c.id,
    c.name,
    c.surname,
    COUNT(o.order_id) AS total_orders
FROM opt_clients c
         JOIN opt_orders o ON o.client_id = c.id
         JOIN opt_products p ON o.product_id = p.product_id
WHERE p.product_category = 'Category1'
  AND o.order_date > DATE '2025-01-01'
GROUP BY c.id, c.name, c.surname
ORDER BY total_orders DESC
LIMIT 5;


CREATE INDEX IF NOT EXISTS idx_custom_orders_date ON opt_orders(order_date);
CREATE INDEX IF NOT EXISTS idx_custom_products_cat ON opt_products(product_category);
CREATE INDEX IF NOT EXISTS idx_custom_orders_client ON opt_orders(client_id);

DROP INDEX IF EXISTS idx_opt_orders_order_date;
DROP INDEX IF EXISTS idx_opt_orders_product_id;
DROP INDEX IF EXISTS idx_opt_orders_client_id;

EXPLAIN ANALYZE
WITH filtered_sales AS (
    SELECT
        o.client_id,
        COUNT(*) as category_orders_count
    FROM opt_orders o
             JOIN opt_products p ON o.product_id = p.product_id
    WHERE p.product_category = 'Category1'
      AND o.order_date > DATE '2025-01-01'
    GROUP BY o.client_id
)
SELECT
    c.id,
    c.name,
    c.surname,
    f.category_orders_count as total_orders
FROM filtered_sales f
         JOIN opt_clients c ON f.client_id = c.id
ORDER BY total_orders DESC
LIMIT 5;


SET enable_hashjoin = OFF;
EXPLAIN ANALYZE
WITH filtered_sales AS (
    SELECT
        o.client_id,
        COUNT(*) as category_orders_count
    FROM opt_orders o
             JOIN opt_products p ON o.product_id = p.product_id
    WHERE p.product_category = 'Category1'
      AND o.order_date > DATE '2025-01-01'
    GROUP BY o.client_id
)
SELECT
    c.id,
    c.name,
    c.surname,
    f.category_orders_count as total_orders
FROM filtered_sales f
         JOIN opt_clients c ON f.client_id = c.id
ORDER BY total_orders DESC
LIMIT 5;
SET enable_hashjoin = ON;
